# Generated by Django 4.2.30 on 2026-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worndly', '0002_game_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='extra_plays_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
